name: using-qiime2-dev
channels:
- https://packages.qiime2.org/qiime2/2025.7/tiny/passed
- conda-forge
- bioconda
dependencies:
  - qiime2-tiny
  - jupyter-book
  - pip
  - pip:
    - q2doc @ git+https://github.com/qiime2/sphinx-ext-qiime2.git@master
    - q2-dwq2 @ git+https://github.com/caporaso-lab/q2-dwq2.git@main
